### ISSUE TITLE
Crash at JSON.parse

### ISSUE THREAD

**Issue by bshevchuk** [usefomo/fomo-nodejs-sdk#1]
Version 1.0.3
Sometimes our application crashes with the error
```
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/mnt/app/node_modules/fomo-nodejs-sdk/lib/index.js:61:31)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

in index.js this lines are 

```
res.on('end', function () {
     callback(JSON.parse(response), null);
});
```

Please run JSON.parse more safely (e.g. wrap with try-catch).

Thanks.

**Comment by ryanckulp** [comment]
thanks @deodatus. @dincek can you take a look?

**Comment by dincek** [comment]
Resolved: https://github.com/usefomo/fomo-nodejs-sdk/pull/2
